### ISSUE TITLE
Any lwm2m Bootstrap support yet?

### ISSUE THREAD

**Issue by ehirdoy** [PeterEB/coap-node#3]
Hi Peter,

I've just started to play with your coap-node against leshan server.
It worked well. Thanks. Appreciated.

One thing,
It seems that this coap-node lwm2m client doesn't support Bootstrap(?)
I'm considering some mass registration measurement(scalability), which requires BSS too,
at least for our experiment.

Do you have any plan to support BootStrap in your coap-node(lwm2m client)?
If not, how much effort do you expect to implement Bootstrap only in lwm2m client,
assuming that, leshan(+bootstrap) server is used in this case.

Any info would be really appreciated.

**Comment by PeterEB** [comment]
Hi ehirdoy,

  Thanks for your feedback, it's good to hear that coap-node works well with Leshan.

  I've studied the spec. And found that may be not so difficult for me to implement a BootStrap server and add the feature to coap-node. I already have a small plan to do it!  It may take me around 2 months to get it done, since I'm a bit busy recently. And contributions are welcome if you like to work it out with me. :smile: 

  I'll let you know when update comes up for you to try it out then.

**Comment by PeterEB** [comment]
Hi @ehirdoy, 

I implement a Bootstrap Server [**lwm2m-bs-server**](https://github.com/PeterEB/lwm2m-bs-server). And **coap-shepherd** and **coap-node** have new version. 

**lwm2m-bs-server** is a Bootstrap Server. It can configures client bootstrap information and configures the LwM2M Client.

In the latest version **coap-node**, it support mulitple servers, factory bootstrap and client initiated bootstrap. 

If you have any question or suggestion, please let me know. Thacks!
